language: node_js
node_js: 10

services:
  - docker

cache:
  directories: node_modules

install:
  - npm install

script:
  - npm run build
  - npm run test

after_success:
  - docker build -t sankin/react-ci .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sankin/react-ci
