language: ruby

services:
  - docker

before_install:
  - docker build -t sankin/react-ci .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sankin/react-ci
